name: myenv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - langchain
      - pymongo
      - langchain-google-genai
      - langchain-community
      - pypdf
      - PyPDF2
      - fitz
      - pymupdf
